#!/usr/bin/env python3
"""
Quality Controller — Consensus Pipeline v0.6.2

Implements the review-rejection pipeline: hard_filter → llm_classify → tag_layer → validate_citations
Resolves the v5.1 issue of irrelevant papers mixing into CSV/charts
"""
import json
import os
import re
import csv
from typing import List, Dict, Any, Tuple, Optional
from datetime import datetime


class QualityController:
    """
    Quality Controller

    Three-layer filtering + citation validation:
    1. hard_filter: Papers matching exclusion signals are immediately rejected
    2. llm_classify: LLM binary classification for domain relevance
    3. tag_layer: Label papers as core/method/background tiers
    4. validate_citations: Validate report citations against CSV consistency
    """

    def __init__(self, llm_call_fn, domain_config: Dict[str, Any], output_dir: str):
        """
        Args:
            llm_call_fn: LLM call function (system_prompt, user_message, temperature) -> str
            domain_config: Domain configuration (generated by domain_config_generator)
            output_dir: Output directory
        """
        self.llm_call_fn = llm_call_fn
        self.domain_config = domain_config
        self.output_dir = output_dir
        self.dedup_registry = {"seen": [], "excluded": []}

    def hard_filter(self, papers: list) -> Tuple[list, list]:
        """
        Hard filter: papers matching domain_config['exclusion_signals'] are immediately scored 0.0 and rejected.

        Args:
            papers: List of PaperCandidate objects

        Returns:
            (filtered_papers, excluded_list)
        """
        exclusion_signals = self.domain_config.get("exclusion_signals", [])
        if not exclusion_signals:
            return papers, []

        filtered = []
        excluded = []

        for p in papers:
            text = (p.title + " " + (p.abstract or "")).lower()
            hit = False
            for signal in exclusion_signals:
                if signal.lower() in text:
                    hit = True
                    break

            if hit:
                excluded.append(p)
                # Record in dedup registry to avoid re-fetching during supplementary searches
                self.dedup_registry["excluded"].append({
                    "title": p.title,
                    "doi": p.doi,
                    "reason": "hard_filter: exclusion_signal hit",
                })
            else:
                filtered.append(p)
                self.dedup_registry["seen"].append({
                    "title": p.title,
                    "doi": p.doi,
                })

        return filtered, excluded

    def llm_classify(self, papers: list) -> Tuple[list, list]:
        """
        LLM binary classification: "Does this paper belong to the target domain? Yes/No"

        Sends title+abstract for each paper, asking the LLM to judge yes/no.

        Args:
            papers: List of PaperCandidate objects

        Returns:
            (approved_papers, rejected_list)
        """
        if not papers:
            return [], []

        classify_prompt = self.domain_config.get("llm_classify_prompt", "")
        domain_def = self.domain_config.get("domain_definition", "")

        if not classify_prompt:
            # Skip LLM classification when no prompt template is available
            return papers, []

        approved = []
        rejected = []

        # Batch classification (max 5 papers per batch to avoid oversized prompts)
        batch_size = 5
        for i in range(0, len(papers), batch_size):
            batch = papers[i:i + batch_size]
            paper_descs = []
            for j, p in enumerate(batch):
                abstract_text = (p.abstract or "N/A")[:300]
                paper_descs.append(
                    f"Paper {j+1}:\nTitle: {p.title}\nAbstract: {abstract_text}"
                )

            user_msg = "\n\n".join(paper_descs)
            system_msg = classify_prompt.replace("{domain_definition}", domain_def) if "{domain_definition}" in classify_prompt else classify_prompt

            try:
                response = self.llm_call_fn(system_msg, user_msg, temperature=0.1)
            except Exception as e:
                # On LLM call failure, conservatively approve
                approved.extend(batch)
                continue

            if not response:
                approved.extend(batch)
                continue

            # Parse LLM response, extract classification result for each paper
            for j, p in enumerate(batch):
                # Find the judgment for this paper
                pattern = rf"论文{j+1}.*?[:：]\s*(否|no|不|不相关|不属于)"  # Matches Chinese/English rejection tokens in LLM output
                if re.search(pattern, response.lower()):
                    rejected.append(p)
                    self.dedup_registry["excluded"].append({
                        "title": p.title,
                        "doi": p.doi,
                        "reason": "llm_classify: not in target domain",
                    })
                else:
                    approved.append(p)

        return approved, rejected

    def tag_layer(self, papers: list) -> list:
        """
        Label three tiers: core/method/background

        Based on domain_config['tier_definitions'] keywords:
        - core: Matches core-tier keywords
        - method: Matches method-supplement keywords
        - background: Matches mechanism-background keywords

        Adds a `layer` attribute to each paper object.

        Args:
            papers: List of PaperCandidate objects

        Returns:
            Labeled paper list
        """
        tier_defs = self.domain_config.get("tier_definitions", {})

        core_keywords = []
        method_keywords = []
        background_keywords = []

        if "core" in tier_defs:
            core_keywords = tier_defs["core"].get("keywords", [])
        if "method" in tier_defs:
            method_keywords = tier_defs["method"].get("keywords", [])
        if "background" in tier_defs:
            background_keywords = tier_defs["background"].get("keywords", [])

        for p in papers:
            text = (p.title + " " + (p.abstract or "")).lower()

            # Determine tier by priority: core > method > background
            if any(kw.lower() in text for kw in core_keywords):
                p.layer = "core"
            elif any(kw.lower() in text for kw in method_keywords):
                p.layer = "method"
            elif any(kw.lower() in text for kw in background_keywords):
                p.layer = "background"
            else:
                # Default to background
                p.layer = "background"

        return papers

    def validate_citations(self, report_text: str, papers_csv_path: str) -> str:
        """
        Walk all [N] citations in the report, compare against CSV, remove invalid ones.

        Args:
            report_text: Report text
            papers_csv_path: Path to papers_metadata.csv

        Returns:
            Validated report text
        """
        if not os.path.exists(papers_csv_path):
            return report_text

        # 1. Read valid paper title set from CSV
        csv_titles = set()
        csv_dois = set()
        try:
            with open(papers_csv_path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    title = row.get("title", "").strip().strip('"')
                    doi = row.get("doi", "").strip().strip('"')
                    if title:
                        csv_titles.add(title.lower()[:50])
                    if doi and doi != "N/A":
                        csv_dois.add(doi)
        except Exception:
            return report_text

        # 2. Separate body text from references section
        ref_split = report_text.split("## 参考文献")  # Split at "## References" heading; Chinese header used in generated reports
        body = ref_split[0]
        ref_part = ref_split[-1] if len(ref_split) >= 2 else ""

        # 3. Extract all [N] citations from body text
        cited_indices = set()
        for m in re.finditer(r'\[(\d+)\]', body):
            idx = int(m.group(1))
            cited_indices.add(idx)

        # 4. Validate each citation — remove invalid ones not in CSV
        invalid_indices = set()
        if ref_part:
            for idx in cited_indices:
                # Find the entry for this index in references section
                pattern = rf'\[{idx}\]\s*(.+?)(?:\n|$)'
                match = re.search(pattern, ref_part)
                if match:
                    ref_entry = match.group(1).lower()
                    # Check if this entry matches any paper in CSV
                    found = False
                    for csv_title in csv_titles:
                        if csv_title in ref_entry:
                            found = True
                            break
                    if not found:
                        invalid_indices.add(idx)
                else:
                    # Index not found in references
                    invalid_indices.add(idx)

        # 5. Remove invalid citation markers
        for idx in invalid_indices:
            # Remove orphaned citation markers
            body = re.sub(r'\s*\[' + str(idx) + r'\]\s*', ' ', body)

        # 6. Rebuild the report
        if ref_part:
            # Remove invalid entries from references
            for idx in invalid_indices:
                ref_part = re.sub(rf'^\[{idx}\].*\n?', '', ref_part, flags=re.MULTILINE)

            result = body + "## 参考文献" + ref_part  # "## 参考文献" = "## References" — must match generated report heading
        else:
            result = body

        return result

    def run_qc(self, papers: list) -> Tuple[list, list, Dict[str, Any]]:
        """
        Main pipeline: hard_filter → llm_classify → tag_layer → statistics

        Args:
            papers: List of PaperCandidate objects

        Returns:
            (cleaned_papers, excluded_ids, stats)
            - If valid count >= 15 → pass
            - If valid count < 15 → return excluded_ids + suggest new queries
        """
        stats = {
            "input_count": len(papers),
            "hard_filter_excluded": 0,
            "llm_classify_rejected": 0,
            "layer_distribution": {"core": 0, "method": 0, "background": 0},
            "final_count": 0,
            "passed": False,
            "suggested_queries": [],
        }

        # Step 1: hard_filter
        papers, excluded_hard = self.hard_filter(papers)
        stats["hard_filter_excluded"] = len(excluded_hard)

        # Step 2: llm_classify
        papers, excluded_llm = self.llm_classify(papers)
        stats["llm_classify_rejected"] = len(excluded_llm)

        # Step 3: tag_layer
        papers = self.tag_layer(papers)

        # Count tier distribution
        for p in papers:
            layer = getattr(p, "layer", "background")
            stats["layer_distribution"][layer] = stats["layer_distribution"].get(layer, 0) + 1

        stats["final_count"] = len(papers)
        stats["passed"] = len(papers) >= 15

        # If valid < 15, suggest new queries from domain_config query_rotation
        if len(papers) < 15:
            query_rotation = self.domain_config.get("query_rotation", [])
            stats["suggested_queries"] = query_rotation[:3] if query_rotation else []

        # Collect all excluded IDs
        excluded_ids = [p.doi or p.title[:30] for p in excluded_hard + excluded_llm]

        # Save QC statistics log
        self._save_qc_log(stats, excluded_hard, excluded_llm)

        return papers, excluded_ids, stats

    def _save_qc_log(self, stats, excluded_hard, excluded_llm):
        """Save QC audit log"""
        log_path = os.path.join(self.output_dir, "qc_audit_log.json")
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "stats": stats,
            "hard_filtered": [
                {"title": p.title, "doi": p.doi, "journal": p.journal}
                for p in excluded_hard
            ],
            "llm_rejected": [
                {"title": p.title, "doi": p.doi, "journal": p.journal}
                for p in excluded_llm
            ],
        }

        # Append write
        existing = []
        if os.path.exists(log_path):
            try:
                with open(log_path, "r", encoding="utf-8") as f:
                    existing = json.load(f)
                if not isinstance(existing, list):
                    existing = [existing]
            except Exception:
                existing = []

        existing.append(log_entry)

        with open(log_path, "w", encoding="utf-8") as f:
            json.dump(existing, f, ensure_ascii=False, indent=2)
