"""
期刊质量分级注册表 — Consensus Pipeline v5.1

独立的期刊注册表模块，避免 journal_classifier ↔ search_engine 循环导入。
v5.1: 从11个扩展到224+个期刊，覆盖CS/AI/能源/经济/管理/环境/统计/运筹/中文CSSCI

数据来源：
- 能源经济学领域：人工校验（2026-07-15）
- 扩展期刊：科研助理提供的224期刊扩展注册表（2026-07-15）
- 动态补充：通过 easyScholar API 实时查询
"""

JOURNAL_QUALITY_REGISTRY = {
    # === S级：能源经济学核心 ===
    "Energy Economics": {"level": "S", "if_2026": 9.0, "jcr": "Q1", "note": "能源经济学旗舰期刊"},
    "Energy Policy": {"level": "S", "if_2026": 9.3, "jcr": "Q1", "note": "能源政策"},
    "Applied Energy": {"level": "S", "if_2026": 11.2, "jcr": "Q1", "note": "能源应用"},
    "Renewable and Sustainable Energy Reviews": {"level": "S", "if_2026": 15.9, "jcr": "Q1", "note": "可再生能源综述"},
    "Global Environmental Change": {"level": "S", "if_2026": 8.9, "jcr": "Q1", "note": "全球环境变化"},
    "American Economic Review": {"level": "S", "if_2026": 11.5, "jcr": "Q1", "note": "经济学顶刊"},
    "Econometrica": {"level": "S", "if_2026": 8.6, "jcr": "Q1", "note": "计量经济学顶刊"},
    "Journal of Political Economy": {"level": "S", "if_2026": 9.8, "jcr": "Q1", "note": "政治经济学顶刊"},
    "Quarterly Journal of Economics": {"level": "S", "if_2026": 13.2, "jcr": "Q1", "note": "经济学顶刊"},
    "Review of Economic Studies": {"level": "S", "if_2026": 7.5, "jcr": "Q1", "note": "经济研究评论"},
    "Journal of Econometrics": {"level": "S", "if_2026": 6.8, "jcr": "Q1", "note": "计量经济学"},
    "Journal of Economic Literature": {"level": "S", "if_2026": 10.8, "jcr": "Q1", "note": "经济学文献综述"},
    "Journal of Economic Perspectives": {"level": "S", "if_2026": 8.9, "jcr": "Q1", "note": "经济学展望"},
    "Annual Review of Economics": {"level": "S", "if_2026": 9.8, "jcr": "Q1", "note": "经济学年度评论"},
    "Nature": {"level": "S", "if_2026": 64.8, "jcr": "Q1", "note": "综合顶刊，能源+ML交叉论文"},
    "Science": {"level": "S", "if_2026": 56.9, "jcr": "Q1", "note": "综合顶刊"},
    "Nature Communications": {"level": "S", "if_2026": 16.6, "jcr": "Q1", "note": "综合子刊"},
    "PNAS (Proceedings of the National Academy of Sciences)": {"level": "S", "if_2026": 11.1, "jcr": "Q1", "note": "美国科学院院刊"},
    "Nature Energy": {"level": "S", "if_2026": 56.3, "jcr": "Q1", "note": "能源子刊，主要学科energy-econ"},
    "Nature Climate Change": {"level": "S", "if_2026": 30.3, "jcr": "Q1", "note": "气候变化子刊，主要学科environmental"},
    "Nature Sustainability": {"level": "S", "if_2026": 27.6, "jcr": "Q1", "note": "可持续子刊，主要学科environmental"},

    # === A级 ===
    "NeurIPS (Conference on Neural Information Processing Systems)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；ML/DL领域顶会，方法论创新优于期刊"},
    "ICML (International Conference on Machine Learning)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；ML理论/方法顶会"},
    "ICLR (International Conference on Learning Representations)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；DL表征学习顶会"},
    "AAAI Conference on Artificial Intelligence": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；AI综合顶会"},
    "IJCAI (International Joint Conference on AI)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；AI综合顶会"},
    "CVPR (Conference on Computer Vision and Pattern Recognition)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；计算机视觉顶会，时间序列/图像分析相关"},
    "ACL (Association for Computational Linguistics)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；NLP顶会，文本分析相关"},
    "KDD (ACM SIGKDD Conference)": {"level": "A", "if_2026": None, "jcr": "", "note": "会议；数据挖掘顶会"},
    "Journal of Machine Learning Research (JMLR)": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "ML理论顶刊，开源"},
    "IEEE Transactions on Neural Networks and Learning Systems (TNNLS)": {"level": "A", "if_2026": 10.4, "jcr": "Q1", "note": "神经网络与学习系统"},
    "Artificial Intelligence": {"level": "A", "if_2026": 14.0, "jcr": "Q1", "note": "AI领域旗舰期刊"},
    "Machine Learning": {"level": "A", "if_2026": 5.2, "jcr": "Q1", "note": "ML经典期刊"},
    "Neural Networks": {"level": "A", "if_2026": 8.2, "jcr": "Q1", "note": "神经网络"},
    "Pattern Recognition": {"level": "A", "if_2026": 8.5, "jcr": "Q1", "note": "模式识别"},
    "IEEE Transactions on Knowledge and Data Engineering (TKDE)": {"level": "A", "if_2026": 9.2, "jcr": "Q1", "note": "数据工程与知识发现"},
    "ACM Computing Surveys": {"level": "A", "if_2026": 16.3, "jcr": "Q1", "note": "计算综述"},
    "IEEE Transactions on Fuzzy Systems": {"level": "A", "if_2026": 11.6, "jcr": "Q1", "note": "模糊系统"},
    "Expert Systems with Applications": {"level": "A", "if_2026": 8.5, "jcr": "Q1", "note": "专家系统应用"},
    "Engineering Applications of Artificial Intelligence": {"level": "A", "if_2026": 7.8, "jcr": "Q1", "note": "AI工程应用"},
    "Applied Soft Computing": {"level": "A", "if_2026": 8.3, "jcr": "Q1", "note": "软计算"},
    "Information Sciences": {"level": "A", "if_2026": 8.8, "jcr": "Q1", "note": "信息科学"},
    "Knowledge-Based Systems": {"level": "A", "if_2026": 8.2, "jcr": "Q1", "note": "知识系统"},
    "Data Mining and Knowledge Discovery": {"level": "A", "if_2026": 5.4, "jcr": "Q1", "note": "数据挖掘"},
    "ACM Transactions on Intelligent Systems and Technology": {"level": "A", "if_2026": 5.8, "jcr": "Q1", "note": "智能系统"},
    "Journal of Artificial Intelligence Research (JAIR)": {"level": "A", "if_2026": 4.8, "jcr": "Q1", "note": "AI研究"},
    "Swarm and Evolutionary Computation": {"level": "A", "if_2026": 8.9, "jcr": "Q1", "note": "群智能与进化计算"},
    "IEEE Computational Intelligence Magazine": {"level": "A", "if_2026": 9.3, "jcr": "Q1", "note": "计算智能"},
    "International Journal of Intelligent Systems": {"level": "A", "if_2026": 7.2, "jcr": "Q1", "note": "智能系统"},
    "IEEE Transactions on Emerging Topics in Computational Intelligence": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "计算智能新兴主题"},
    "Energy": {"level": "A", "if_2026": 9.0, "jcr": "Q1", "note": "能源综合"},
    "Renewable Energy": {"level": "A", "if_2026": 8.7, "jcr": "Q1", "note": "可再生能源"},
    "Journal of Cleaner Production": {"level": "A", "if_2026": 11.1, "jcr": "Q1", "note": "清洁生产"},
    "Resources, Conservation and Recycling": {"level": "A", "if_2026": 13.2, "jcr": "Q1", "note": "资源循环"},
    "IEEE Transactions on Power Systems": {"level": "A", "if_2026": 7.6, "jcr": "Q1", "note": "电力系统"},
    "IEEE Transactions on Smart Grid": {"level": "A", "if_2026": 9.4, "jcr": "Q1", "note": "智能电网"},
    "International Journal of Electrical Power & Energy Systems": {"level": "A", "if_2026": 5.8, "jcr": "Q1", "note": "电力与能源系统"},
    "Energy Conversion and Management": {"level": "A", "if_2026": 10.4, "jcr": "Q1", "note": "能源转换与管理"},
    "Journal of Energy Storage": {"level": "A", "if_2026": 9.4, "jcr": "Q1", "note": "储能"},
    "Energy and AI": {"level": "A", "if_2026": 8.3, "jcr": "Q1", "note": "能源+AI交叉"},
    "Advances in Applied Energy": {"level": "A", "if_2026": 7.8, "jcr": "Q1", "note": "应用能源进展"},
    "Energy Research & Social Science": {"level": "A", "if_2026": 6.9, "jcr": "Q1", "note": "能源社会科学"},
    "Environmental Innovation and Societal Transitions": {"level": "A", "if_2026": 7.5, "jcr": "Q1", "note": "环境创新"},
    "Technological Forecasting and Social Change": {"level": "A", "if_2026": 10.5, "jcr": "Q1", "note": "技术预测"},
    "Review of Economics and Statistics": {"level": "A", "if_2026": 5.9, "jcr": "Q1", "note": "经济学与统计评论"},
    "Economic Journal": {"level": "A", "if_2026": 5.4, "jcr": "Q1", "note": "经济学杂志"},
    "European Economic Review": {"level": "A", "if_2026": 4.5, "jcr": "Q1", "note": "欧洲经济评论"},
    "International Economic Review": {"level": "A", "if_2026": 4.2, "jcr": "Q1", "note": "国际经济评论"},
    "Journal of Economic Growth": {"level": "A", "if_2026": 5.6, "jcr": "Q1", "note": "经济增长"},
    "Journal of Human Resources": {"level": "A", "if_2026": 5.3, "jcr": "Q1", "note": "人力资源"},
    "Journal of Development Economics": {"level": "A", "if_2026": 5.2, "jcr": "Q1", "note": "发展经济学"},
    "Journal of Public Economics": {"level": "A", "if_2026": 4.8, "jcr": "Q1", "note": "公共经济学"},
    "Journal of Environmental Economics and Management": {"level": "A", "if_2026": 5.8, "jcr": "Q1", "note": "环境经济学"},
    "Resource and Energy Economics": {"level": "A", "if_2026": 4.1, "jcr": "Q1", "note": "资源与能源经济学"},
    "American Economic Journal: Applied Economics": {"level": "A", "if_2026": 7.2, "jcr": "Q1", "note": "应用经济学"},
    "American Economic Journal: Economic Policy": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "经济政策"},
    "Journal of the European Economic Association": {"level": "A", "if_2026": 5.5, "jcr": "Q1", "note": "欧洲经济协会"},
    "Econometric Theory": {"level": "A", "if_2026": 3.2, "jcr": "Q1", "note": "计量理论"},
    "Journal of Applied Econometrics": {"level": "A", "if_2026": 4.0, "jcr": "Q1", "note": "应用计量经济学"},
    "World Development": {"level": "A", "if_2026": 6.0, "jcr": "Q1", "note": "世界发展"},
    "Oxford Review of Economic Policy": {"level": "A", "if_2026": 4.5, "jcr": "Q1", "note": "牛津经济政策评论"},
    "Organization Studies": {"level": "A", "if_2026": 5.6, "jcr": "Q1", "note": "组织研究"},
    "Journal of Management Studies": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "管理研究"},
    "Research Policy": {"level": "A", "if_2026": 9.5, "jcr": "Q1", "note": "研究政策，创新管理"},
    "Journal of Business Ethics": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "商业伦理"},
    "Journal of Management": {"level": "A", "if_2026": 9.0, "jcr": "Q1", "note": "管理学"},
    "British Journal of Management": {"level": "A", "if_2026": 5.5, "jcr": "Q1", "note": "英国管理"},
    "International Journal of Management Reviews": {"level": "A", "if_2026": 8.5, "jcr": "Q1", "note": "管理评论"},
    "Academy of Management Perspectives": {"level": "A", "if_2026": 6.2, "jcr": "Q1", "note": "管理视角"},
    "Journal of Operations Management": {"level": "A", "if_2026": 7.8, "jcr": "Q1", "note": "运营管理"},
    "Production and Operations Management": {"level": "A", "if_2026": 5.2, "jcr": "Q1", "note": "生产与运营管理"},
    "Omega": {"level": "A", "if_2026": 8.2, "jcr": "Q1", "note": "管理科学"},
    "IEEE Transactions on Engineering Management": {"level": "A", "if_2026": 6.5, "jcr": "Q1", "note": "工程管理"},
    "Technovation": {"level": "A", "if_2026": 8.4, "jcr": "Q1", "note": "技术创新"},
    "R&D Management": {"level": "A", "if_2026": 5.5, "jcr": "Q1", "note": "研发管理"},
    "Environmental Research Letters": {"level": "A", "if_2026": 6.8, "jcr": "Q1", "note": "环境研究快报"},
    "Science of the Total Environment": {"level": "A", "if_2026": 9.8, "jcr": "Q1", "note": "总体环境科学"},
    "Atmospheric Environment": {"level": "A", "if_2026": 5.5, "jcr": "Q1", "note": "大气环境"},
    "Environmental Pollution": {"level": "A", "if_2026": 8.9, "jcr": "Q1", "note": "环境污染"},
    "Journal of Environmental Management": {"level": "A", "if_2026": 8.7, "jcr": "Q1", "note": "环境管理"},
    "Ecological Economics": {"level": "A", "if_2026": 6.6, "jcr": "Q1", "note": "生态经济学"},
    "Climatic Change": {"level": "A", "if_2026": 5.3, "jcr": "Q1", "note": "气候变化"},
    "International Journal of Greenhouse Gas Control": {"level": "A", "if_2026": 4.8, "jcr": "Q1", "note": "温室气体控制"},
    "Journal of Industrial Ecology": {"level": "A", "if_2026": 5.8, "jcr": "Q1", "note": "产业生态学"},
    "Environmental Impact Assessment Review": {"level": "A", "if_2026": 6.2, "jcr": "Q1", "note": "环境影响评估"},
    "Waste Management": {"level": "A", "if_2026": 8.1, "jcr": "Q1", "note": "废物管理"},
    "Resources Policy": {"level": "A", "if_2026": 8.6, "jcr": "Q1", "note": "资源政策"},
    "Land Use Policy": {"level": "A", "if_2026": 6.0, "jcr": "Q1", "note": "土地利用政策"},
    "Environmental Modelling & Software": {"level": "A", "if_2026": 5.6, "jcr": "Q1", "note": "环境建模与软件"},
    "Earth's Future": {"level": "A", "if_2026": 8.8, "jcr": "Q1", "note": "地球未来"},
    "One Earth": {"level": "A", "if_2026": 14.0, "jcr": "Q1", "note": "地球可持续"},
    "Communications Earth & Environment": {"level": "A", "if_2026": 8.0, "jcr": "Q1", "note": "地球与环境通讯"},
    "npj Climate and Atmospheric Science": {"level": "A", "if_2026": 7.5, "jcr": "Q1", "note": "气候与大气科学"},
    "中国工业经济": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "世界经济": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济学动态": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "数量经济技术经济研究": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "中国软科学": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "科研管理": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "科学学研究": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "中国管理科学": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "系统工程理论与实践": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "资源科学": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "地理学报": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "生态学报": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "中国人口·资源与环境": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "管理科学学报": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "南开管理评论": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "金融研究": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "统计研究": {"level": "A", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "Biometrika": {"level": "A", "if_2026": 3.5, "jcr": "Q1", "note": "生物统计"},
    "Journal of the Royal Statistical Society: Series A (Statistics in Society)": {"level": "A", "if_2026": 3.2, "jcr": "Q1", "note": "社会统计"},
    "Journal of the Royal Statistical Society: Series C (Applied Statistics)": {"level": "A", "if_2026": 2.8, "jcr": "Q2", "note": "应用统计"},
    "Annals of Applied Statistics": {"level": "A", "if_2026": 3.0, "jcr": "Q1", "note": "应用统计学年鉴"},
    "Computational Statistics & Data Analysis": {"level": "A", "if_2026": 2.5, "jcr": "Q1", "note": "计算统计与数据分析"},
    "Statistics and Computing": {"level": "A", "if_2026": 3.2, "jcr": "Q1", "note": "统计与计算"},
    "Journal of Computational and Graphical Statistics": {"level": "A", "if_2026": 2.8, "jcr": "Q1", "note": "计算与图形统计"},
    "Statistical Science": {"level": "A", "if_2026": 3.5, "jcr": "Q1", "note": "统计科学"},
    "Journal of Business & Economic Statistics": {"level": "A", "if_2026": 5.2, "jcr": "Q1", "note": "商业与经济统计"},
    "Statistics in Medicine": {"level": "A", "if_2026": 2.7, "jcr": "Q1", "note": "医学统计"},
    "Statistical Methods in Medical Research": {"level": "A", "if_2026": 2.5, "jcr": "Q1", "note": "医学统计方法"},
    "SIAM Journal on Optimization": {"level": "A", "if_2026": 3.2, "jcr": "Q1", "note": "优化"},
    "INFORMS Journal on Computing": {"level": "A", "if_2026": 3.6, "jcr": "Q1", "note": "计算运筹"},
    "Annals of Operations Research": {"level": "A", "if_2026": 4.2, "jcr": "Q1", "note": "运筹学年鉴"},
    "Computers & Operations Research": {"level": "A", "if_2026": 4.5, "jcr": "Q1", "note": "计算机与运筹"},
    "Transportation Research Part E": {"level": "A", "if_2026": 8.5, "jcr": "Q1", "note": "交通运筹"},
    "Journal of the Operational Research Society": {"level": "A", "if_2026": 3.5, "jcr": "Q1", "note": "运筹学会"},
    "Science Advances": {"level": "A", "if_2026": 13.6, "jcr": "Q1", "note": "科学进展"},
    "iScience": {"level": "A", "if_2026": 5.8, "jcr": "Q1", "note": "Cell综合子刊"},

    # === S级：中文CSSCI顶刊 ===
    "经济研究": {"level": "S", "if_2026": None, "jcr": "CSSCI", "note": "经济学顶刊，CSSCI"},
    "管理世界": {"level": "S", "if_2026": None, "jcr": "CSSCI", "note": "管理学顶刊，CSSCI"},
    "中国社会科学": {"level": "S", "if_2026": None, "jcr": "CSSCI", "note": "综合社科顶刊，CSSCI"},

    # === B级 ===
    "Neurocomputing": {"level": "B", "if_2026": 5.5, "jcr": "Q1", "note": "神经计算"},
    "Neural Computing and Applications": {"level": "B", "if_2026": 5.6, "jcr": "Q1", "note": "神经计算应用"},
    "Cognitive Computation": {"level": "B", "if_2026": 4.2, "jcr": "Q1", "note": "认知计算"},
    "AI Magazine": {"level": "B", "if_2026": 2.1, "jcr": "Q3", "note": "AI综述"},
    "Complex & Intelligent Systems": {"level": "B", "if_2026": 4.5, "jcr": "Q1", "note": "复杂智能系统"},
    "Electric Power Systems Research": {"level": "B", "if_2026": 3.9, "jcr": "Q1", "note": "电力系统研究"},
    "Applied Thermal Engineering": {"level": "B", "if_2026": 6.4, "jcr": "Q1", "note": "应用热工程"},
    "Sustainable Energy Technologies and Assessments": {"level": "B", "if_2026": 7.2, "jcr": "Q1", "note": "可持续能源技术"},
    "Energy Reports": {"level": "B", "if_2026": 5.2, "jcr": "Q1", "note": "能源报告"},
    "Energy Strategy Reviews": {"level": "B", "if_2026": 5.5, "jcr": "Q1", "note": "能源战略"},
    "Energy for Sustainable Development": {"level": "B", "if_2026": 4.6, "jcr": "Q1", "note": "可持续能源发展"},
    "Utilities Policy": {"level": "B", "if_2026": 3.2, "jcr": "Q2", "note": "公用事业政策"},
    "Climate Policy": {"level": "B", "if_2026": 4.2, "jcr": "Q1", "note": "气候政策"},
    "Carbon Management": {"level": "B", "if_2026": 3.5, "jcr": "Q2", "note": "碳管理"},
    "Greenhouse Gases: Science and Technology": {"level": "B", "if_2026": 3.1, "jcr": "Q2", "note": "温室气体"},
    "Mitigation and Adaptation Strategies for Global Change": {"level": "B", "if_2026": 4.0, "jcr": "Q1", "note": "减缓与适应"},
    "International Journal of Sustainable Energy": {"level": "B", "if_2026": 2.8, "jcr": "Q3", "note": "可持续能源"},
    "Frontiers in Energy Research": {"level": "B", "if_2026": 3.4, "jcr": "Q2", "note": "能源研究前沿"},
    "Sustainable Energy & Fuels": {"level": "B", "if_2026": 5.1, "jcr": "Q1", "note": "可持续能源与燃料"},
    "Journal of Modern Power Systems and Clean Energy": {"level": "B", "if_2026": 4.8, "jcr": "Q1", "note": "现代电力系统与清洁能源"},
    "CSEE Journal of Power and Energy Systems": {"level": "B", "if_2026": 5.8, "jcr": "Q1", "note": "中国电机工程学会电力与能源系统"},
    "Oxford Bulletin of Economics and Statistics": {"level": "B", "if_2026": 2.8, "jcr": "Q2", "note": "牛津经济与统计"},
    "Econometric Reviews": {"level": "B", "if_2026": 2.5, "jcr": "Q2", "note": "计量评论"},
    "Empirical Economics": {"level": "B", "if_2026": 2.2, "jcr": "Q2", "note": "实证经济学"},
    "Applied Economics": {"level": "B", "if_2026": 2.0, "jcr": "Q2", "note": "应用经济学"},
    "Applied Economics Letters": {"level": "B", "if_2026": 1.3, "jcr": "Q3", "note": "应用经济学快报"},
    "Economics Letters": {"level": "B", "if_2026": 1.8, "jcr": "Q2", "note": "经济学快报"},
    "Management and Organization Review": {"level": "B", "if_2026": 3.5, "jcr": "Q2", "note": "管理与组织评论"},
    "Asian Business & Management": {"level": "B", "if_2026": 3.2, "jcr": "Q2", "note": "亚洲商业管理"},
    "Ecological Indicators": {"level": "B", "if_2026": 5.8, "jcr": "Q1", "note": "生态指标"},
    "Natural Hazards": {"level": "B", "if_2026": 3.5, "jcr": "Q2", "note": "自然灾害"},
    "管理评论": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "会计研究": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "财经研究": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济管理": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "改革": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济科学": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济评论": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济学家": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "当代经济科学": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "财经科学": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "经济纵横": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "城市与环境研究": {"level": "B", "if_2026": None, "jcr": "", "note": "CSSCI"},
    "Scandinavian Journal of Statistics": {"level": "B", "if_2026": 2.1, "jcr": "Q2", "note": "斯堪的纳维亚统计"},
    "Econometrics and Statistics": {"level": "B", "if_2026": 2.0, "jcr": "Q2", "note": "计量经济学与统计"},
    "TEST": {"level": "B", "if_2026": 1.8, "jcr": "Q3", "note": "西班牙统计"},
    "Journal of Optimization Theory and Applications": {"level": "B", "if_2026": 2.8, "jcr": "Q2", "note": "优化理论与应用"},
    "Optimization Letters": {"level": "B", "if_2026": 2.2, "jcr": "Q2", "note": "优化快报"},
    "Journal of Global Optimization": {"level": "B", "if_2026": 2.8, "jcr": "Q2", "note": "全局优化"},
    "Networks and Spatial Economics": {"level": "B", "if_2026": 2.5, "jcr": "Q2", "note": "网络与空间经济"},
    "OR Spectrum": {"level": "B", "if_2026": 2.8, "jcr": "Q2", "note": "运筹光谱"},
    "4OR": {"level": "B", "if_2026": 2.0, "jcr": "Q2", "note": "运筹学季刊"},
    "TOP": {"level": "B", "if_2026": 1.8, "jcr": "Q3", "note": "西班牙运筹"},
    "Optimization Methods and Software": {"level": "B", "if_2026": 2.5, "jcr": "Q2", "note": "优化方法与软件"},
    "PLOS ONE": {"level": "B", "if_2026": 3.7, "jcr": "Q2", "note": "开源综合，谨慎收录"},
    "Royal Society Open Science": {"level": "B", "if_2026": 3.2, "jcr": "Q2", "note": "皇家学会开源"},
    "Scientific Reports": {"level": "B", "if_2026": 4.6, "jcr": "Q1", "note": "综合子刊"},

    # === v5.1.2新增：科研助理注册表扩展（管理/统计/运筹/环境顶刊）===
    "IEEE Transactions on Pattern Analysis and Machine Intelligence (TPAMI)": {"level": "S", "if_2026": 24.0, "jcr": "Q1", "note": "AI/ML/模式识别顶刊"},
    "IEEE Transactions on Pattern Analysis and Machine Intelligence": {"level": "S", "if_2026": 24.0, "jcr": "Q1", "note": "AI/ML/模式识别顶刊"},
    "Academy of Management Journal": {"level": "S", "if_2026": 10.5, "jcr": "Q1", "note": "管理学顶刊"},
    "Academy of Management Review": {"level": "S", "if_2026": 12.0, "jcr": "Q1", "note": "管理评论顶刊"},
    "Administrative Science Quarterly": {"level": "S", "if_2026": 9.3, "jcr": "Q1", "note": "管理科学"},
    "Strategic Management Journal": {"level": "S", "if_2026": 8.8, "jcr": "Q1", "note": "战略管理"},
    "Organization Science": {"level": "S", "if_2026": 7.5, "jcr": "Q1", "note": "组织科学"},
    "Management Science": {"level": "S", "if_2026": 7.2, "jcr": "Q1", "note": "管理科学"},
    "Environmental Science & Technology": {"level": "S", "if_2026": 11.4, "jcr": "Q1", "note": "环境科学与技术"},
    "Annual Review of Environment and Resources": {"level": "S", "if_2026": 14.5, "jcr": "Q1", "note": "环境与资源年度评论"},
    "Journal of the Royal Statistical Society: Series B (Statistical Methodology)": {"level": "S", "if_2026": 5.8, "jcr": "Q1", "note": "统计方法学顶刊"},
    "Annals of Statistics": {"level": "S", "if_2026": 4.5, "jcr": "Q1", "note": "统计学年鉴"},
    "Journal of the American Statistical Association (JASA)": {"level": "S", "if_2026": 4.8, "jcr": "Q1", "note": "美国统计学会"},
    "Operations Research": {"level": "S", "if_2026": 4.5, "jcr": "Q1", "note": "运筹学顶刊"},
    "European Journal of Operational Research": {"level": "S", "if_2026": 6.4, "jcr": "Q1", "note": "欧洲运筹学"},
    "Mathematical Programming": {"level": "S", "if_2026": 3.8, "jcr": "Q1", "note": "数学规划"},
    # 别名映射
    "TPAMI": {"level": "S", "if_2026": 24.0, "jcr": "Q1", "note": "别名→IEEE TPAMI"},
    "JASA": {"level": "S", "if_2026": 4.8, "jcr": "Q1", "note": "别名→Journal of the American Statistical Association"},
    "Proceedings of the National Academy of Sciences": {"level": "S", "if_2026": 11.1, "jcr": "Q1", "note": "美国科学院院刊（PNAS全称）"},
    "Proceedings of the National Academy of Sciences of the United States of America": {"level": "S", "if_2026": 11.1, "jcr": "Q1", "note": "PNAS全称变体"},
}